services:
  database:
    image: 
      postgres
    network_mode: bridge
    ports:
       - 5433:5432
    volumes: 
      - db:/var/lib/postgres/data
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecs-task
    container_name: ecs-task
networks:
  postgres:
    driver: bridge
    
volumes:
  db: